### ISSUE TITLE
predict 结果都是111111

### ISSUE THREAD

**Issue by chclock** [tangji08/Attention-OCR#1]
按照readme训练后，结果都是现实1111111
```
images/1.png 
111111111111111 
confifence: D (0 fault: 2%, 1 fault: 14%, 2 faults: 13%, 3 faults: 13%, 3++ faults: 60%)
-----------------------------------------------------------
images/10.png 
111111111111111 
confifence: D (0 fault: 2%, 1 fault: 14%, 2 faults: 13%, 3 faults: 13%, 3++ faults: 60%)
-----------------------------------------------------------
images/46.jpg 
111111111111111 
confifence: D (0 fault: 2%, 1 fault: 14%, 2 faults: 13%, 3 faults: 13%, 3++ faults: 60%)
```
请问是训练集太小的原因吗？请问你的训练集是多大呢

**Comment by tang-ji** [comment]
这样的训练结果应该是训练时间太短，神经网络没有收敛。可以尝试多训练一段时间，等到log.txt里面显示的loss小于0.1之后再进行预测。

**Comment by chclock** [comment]
结果还是有问题，你的训练集也是train中的吗，按readme步骤只跑了150步左右，改了代码强行跑了1000多步：
Saving the model at step 1400.
Step 1401: 10.427s, loss: 2.177871, perplexity: 8.827497.
Step 1402: 10.405s, loss: 2.164262, perplexity: 8.708169.
Step 1403: 10.449s, loss: 2.149662, perplexity: 8.581953.
Step 1404: 10.452s, loss: 2.151817, perplexity: 8.600474.
Global step 1404. Time: 0.417, loss: 0.086436, perplexity: 1.09.
Finishing the training and saving the model at step 1404.
结果
images/1.png 
RRR 
confifence: D (0 fault: 2%, 1 fault: 14%, 2 faults: 13%, 3 faults: 13%, 3++ faults: 60%)
-----------------------------------------------------------
images/10.png 
100000000000000 
confifence: D (0 fault: 2%, 1 fault: 14%, 2 faults: 13%, 3 faults: 13%, 3++ faults: 60%)
-----------------------------------------------------------
images/46.jpg 
000000000000000 
confifence: D (0 fault: 2%, 1 fault: 14%, 2 faults: 13%, 3 faults: 13%, 3++ faults: 60%)
-----------------------------------------------------------

**Comment by tang-ji** [comment]
@chclock 我的训练集综合了icdar13, 标签生成器产生的以及真实标签，总共5万左右的训练图片，迭代大约14万次。

**Comment by chclock** [comment]
果然是我的训练集太小了，不过14万次我的电脑估计要跑2周，请问你能提供下你训练好的model让我学习使用下吗？谢谢。

**Comment by tang-ji** [comment]
我训练好的模型是针对我需要解决的问题，特别生成的训练集进行训练，具体预测结果可见Readme文件的例子。你拿这个模型去测试别的标签没有什么意义。

**Comment by chclock** [comment]
好吧，谢谢
